FROM debian:bullseye-slim AS infisical-builder
RUN apt-get update && apt-get install -y curl bash && \
    curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash && \
    apt-get update && apt-get install -y infisical

FROM ghcr.io/jemmia-diamond/lobehub:latest
COPY --from=infisical-builder /usr/bin/infisical /bin/infisical
ENTRYPOINT ["/bin/infisical", "run", "--projectId", "79601934-6801-4afa-a075-60fcc40d90f8", "--env", "prod", "--path", "/lobehub", "--", "/bin/node"]
CMD ["/app/startServer.js"]
