// Test embedding fixtures — 3072-dim zero vectors for gemini-embedding-2-preview
// These are used in DB integration tests only; real embeddings are generated by the embedding service

export const designThinkingQuery: number[] = Array.from({ length: 3072 }, (_, i) =>
  i === 0 ? 0.1 : 0,
);

export const designThinkingQuery2: number[] = Array.from({ length: 3072 }, (_, i) =>
  i === 1 ? 0.1 : 0,
);

export const codeEmbedding: number[] = Array.from({ length: 3072 }, (_, i) =>
  i === 2 ? 0.1 : 0,
);
