// Test embedding fixtures — 3072-dim zero vectors for gemini-embedding-2-preview
// These are used in DB integration tests only; real embeddings are generated by the embedding service

export const designThinkingQuery: number[] = Array.from({ length: 3072 }, (_, i) => {
  if (i === 0) return 0.9;
  if (i === 1) return 0.4;
  return 0;
});

export const designThinkingQuery2: number[] = Array.from({ length: 3072 }, (_, i) => {
  if (i === 0) return 0.8;
  if (i === 1) return 0.5;
  return 0;
});

export const codeEmbedding: number[] = Array.from({ length: 3072 }, (_, i) => {
  if (i === 2) return 0.9;
  if (i === 3) return 0.4;
  return 0;
});
